### PR TITLE
HDM-429 Use ordered_members when attaching FileSets.

### PR DESCRIPTION
**Pull request by dlpierce**
This is the simplest fix to make our ingests display their related objects in the UI.

Later we may want to refactor to use actors in curation_concerns 1.0.

### CODE REVIEW

**Comment by afred** [comment]
@dlpierce i _think_ that using `ordered_members` instead of `members` here means that under the hood, there is an additional layer of abstraction between the parent and child objects, using what PCDM calls "indirect containers". This layer is effectively a proxy container that allows for ordering.

I'm not sure that we care, just noting that this will have an effect on how things are stored under the hood. At least as far as I understand it.

**Comment by afred** [comment]
@dlpierce weird error on Travis...
```
The log length has exceeded the limit of 4 Megabytes (this usually means that test suite is raising the same exception over and over).
```
Never seen that one before.

**Comment by dlpierce** [comment]
@afred Looks like the solr download stalled, but something invisible gets written to the log? Restarting it even though the push build passed.

**Comment by amolmkhedkar** [comment]
Shall we wait on this till we complete ingest of tars with pres and prod files and add functionality for them as well? @dlpierce @afred

**Comment by afred** [comment]
nah.. merging.

**Pull request merged**
